In [8]:
import pandas as pd

In [9]:
# Read the CSV file
Sep = pd.read_csv("/content/drive/MyDrive/IG /Multable_clients_in_one.csv", index_col=0)

In [10]:
# Drop duplicate rows
No_Dup = Sep.drop_duplicates()

# Initialize an empty list to collect rows
rows_to_add = []

In [11]:
# Iterate through the rows of No_Dup
for index, row in No_Dup.iterrows():
    if "," in row["Client Code"]:
        # Split the 'Client Code' by comma
        split_values = row["Client Code"].split(",")
        # Iterate over each split value and create a new row for each
        for x in split_values:
            # Create a new row with all columns from Sep, updating 'Client Code'
            new_row = row.copy()
            new_row["Client Code"] = x.strip()  # Remove any leading/trailing whitespace
            rows_to_add.append(new_row)
    else:
        # Create a new row with all columns from Sep, no change needed
        rows_to_add.append(row)

In [12]:
# Convert list of rows to a DataFrame
New = pd.DataFrame(rows_to_add)

# Ensure the columns of New are in the same order as Sep
New = New[Sep.columns]

# Save the resulting DataFrame to a new CSV file
New.to_csv('fixed.csv', index=True)  # Save with index to preserve original indexing

# Print the resulting DataFrame (optional)
print(New)

                           Client Code
Fake Moon Landing Co.           ML9853
Fake Moon Landing Co.           ML9844
Jupiter Candy Inc              JC34123
Coldwater Taxes                CW57923
Waterlogged Park               WL68038
Waterlogged Park               WL96832
Waterlogged Park               WL90145
Waterlogged Park               WL09863
Sunset Building Co             SB78932
Surf Cafe                      SC04376
Fish and Chips Cola            FC09435
Fish and Chips Cola            FC90143
Fish and Chips Cola           FC908654
Foggy Mountain Ski Resort     FM856345
Burning Earth Clay            BE985643
Slingshot Taxes               ST954327